### ISSUE TITLE
Disabled apps still accessible on HUD

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-hud#76]
When an app is disabled it is still accessible on HUD.  Is this by design?

**Comment by mparizernc** [comment]
@clarkjefcoat I believe this was something missed. This should be Andy's call what he wants it to do. If we decide not to have it accessible in HUD we would need to come up with some back end logic to remove it from every ones library. We should also have a way to let the users know why it is missing form their HUD. I will say that in legacy if a listing was disabled in the Store it was still available in OWF. I am not saying we should do that just saying what is currently done.

**Comment by TheAndyStumpf** [comment]
If the app is disabled, then the user should not be allowed to use it any longer (or at least until it's up & running again).  Otherwise what's the point of disabling apps?  There should also be a notification that goes out to the users who have favorited it letting them know the app was disabled and why.  That way, a user is not left in the dark wondering what happened, and they can adjust their workflow.

**Comment by mparizernc** [comment]
Currently we have been told that performance is the priority, if this is higher priority we can change direction.  However I am not sure this would required a back end but either way there is workflow to discuss on this. Should the listing if disabled be removed from the bookmarks if so that is a call that can be done through the front end possibly.  Also there is no way at the moment to send a Notification (assuming you are talking about what is implemented) to specific users it goes to everyone as a system wide notification.

**Comment by tonyalletag** [comment]
A listing should be removed from the HUD and Webtop if it is disabled.  The users should still have the listing Bookmark and the listing should be viewable again if the listing becomes enabled.
